docker:
    path: .
id: f4237f65-279f-4b3d-9e5c-23908742bd17
ide:
    filename: ide.yaml
name: capstone-llm-maria
resources:
    path: resources
streaming:
    filename: streaming.yaml
template: ""
version: "0.3"
workflows:
    path: dags
    version: "2"
